# .goreleaser.yaml
version: 2

project_name: myapp

builds:
  - id: myapp
    main: .
    binary: myapp
    env:
      - CGO_ENABLED=0
    goos: ["windows"]
    goarch: ["amd64", "386"]

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["zip"]

checksum:
  name_template: "checksums.txt"
