# .goreleaser.yaml
version: 2

project_name: test

builds:
  - id: testcmd
    main: .
    binary: testcmd
    env:
      - CGO_ENABLED=0
    goos: ["windows"]
    goarch: ["amd64", "386"]
    ldflags:
      - "-s -w"
      - "-X main.version={{ .Version }}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version | trimPrefix \"v\" }}_{{ .Os }}_{{ .Arch }}"
    formats: ["zip"]
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*

checksum:
  name_template: "checksums.txt"
