# .goreleaser.yaml
version: 2

project_name: test

builds:
  - id: test
    main: .
    binary: "{{ .ProjectName }}cmd"
    env:
      - CGO_ENABLED=0
    goos: ["windows"]
    goarch: ["amd64", "386"]

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["zip"]
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"
